dist: xenial
sudo: true

language: minimal 

jobs:
    include:
        - script:
          - travis/ubuntu-18.04
          - source travis/ubuntu-18.04-run
          - run echo "run works"
          - run_script example.sh
        - script:
          - travis/debian-8
          - source travis/debian-8-run
        - script:
          - travis/debian-9
          - source travis/debian-9-run
        - script:
          - travis/debian-10
          - source travis/debian-10-run
        - script:
          - travis/debian-sid
          - source travis/debian-sid-run
        - script:
          - travis/ubuntu-16.04
          - source travis/ubuntu-16.04-run
        - script:
          - travis/ubuntu-18.04
          - source travis/ubuntu-18.04-run
        - script:
          - travis/ubuntu-19.04
          - source travis/ubuntu-19.04-run
