dist: xenial
sudo: true

language: minimal 

jobs:
    include:
        - script:
          - travis/ubuntu-18.04
          - source travis/ubuntu-18.04-run
          - run echo "run works"
          - run_script example.sh
