#!/bin/bash
sudo lxc exec container -- cat /etc/resolv.conf
sudo lxc exec container -- ping 8.8.8.8 -c 2
sudo lxc exec container -- ping google.com -c 2
sudo lxc exec container -- ip a
sudo lxc exec container -- dnf -y update
sudo lxc exec container -- dnf -y upgrade
