#!/bin/bash

IMAGE=${1}

# update
sudo apt-get -qq update > /dev/null
sudo apt-get -qq dist-upgrade > /dev/null
sudo snap refresh > /dev/null

# install lxd
sudo snap install lxd > /dev/null

# initalize lxd
cat << EOF | sudo /snap/bin/lxd init --preseed
config: {}
networks:
- config:
    ipv4.address: auto
    ipv6.address: auto
  description: ""
  managed: false
  name: lxdbr0
  type: ""
storage_pools:
- config:
    source: /var/lib/lxd/storage-pools/default
  description: ""
  name: default
  driver: btrfs
profiles:
- config:
    security.privileged: "true"
  description: ""
  devices:
    eth0:
      name: eth0
      nictype: bridged
      parent: lxdbr0
     type: nic
    root:
      path: /
      pool: default
      type: disk
  name: default
cluster: null
EOF
sudo /snap/bin/lxc --version

# restart lxd
sudo systemctl restart lxd

# debugging
sudo lxc profile show default

# launch lxd container
sudo lxc launch ${IMAGE} container
