#!/bin/bash

IMAGE=${1}

# update
sudo apt-get -qq update
sudo apt-get -qq dist-upgrade

# install lxd
sudo apt-get -qq install lxd

# initalize lxd
yes '' | sudo lxd init

# launch lxd container
sudo lxc launch ${IMAGE} container
