#!/bin/bash

IMAGE=${1}

# update
sudo apt-get -qq update > /dev/null
sudo apt-get -qq dist-upgrade > /dev/null

# install lxd
sudo apt-get -qq install lxd > /dev/null

# initalize lxd
sudo lxd init --auto

# launch lxd container
sudo lxc launch ${IMAGE} container
