#!/usr/bin/env bash

run() {
    sudo lxc exec container -- $*
}    

run_script() {
    if [ ! -f $1 ] ; then
        echo "invalid script path!"
        exit 1
    fi
    while read line ; do
        sudo lxc exec container -- "'${line}'"
    done < $1
}
